# Change these first
owner: ettorestark # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Personal page
    url: https://www.ettorestark.com

assignees: # Users to assign downtime issues (optional)
  - AnandChowdhary

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status monitor
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
